services:
  webapp:
    image: dotlabs/apache:php${DOCKER_PHP_VERSION}
    volumes:
      - ".:/var/www/html"
    depends_on:
      - database
      - redis
    ports:
      - ${DOCKER_WEBAPP_PORT}:80

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - "database-vol:/var/lib/mysql"

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=toor
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "redis-vol:/data"

volumes:
  database-vol:
  redis-vol:
